name = "e2ee-messaging"
main = "src/worker.py"
compatibility_date = "2024-04-05"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "e2ee-convoroom"
database_id = "6607da5e-9cb3-4ad9-97bd-7ff87168cc62"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]
html_handling = "auto-trailing-slash"